(function(){'use strict';
var DATA_URL=(function(){var s=document.currentScript;return s&&s.src?s.src.replace(/app\.js(?:\?.*)?$/,'data.js'):new URL('data.js',location.href).href;})();
function loadData(cb){var s=document.createElement('script');s.src=DATA_URL+'?v=2';s.onload=cb;s.onerror=function(){document.body.setAttribute('data-app-error','data');};document.head.appendChild(s)}
function init(){
 var D=window.RANDOSPINO_DATA||{};
 var $=function(id){return document.getElementById(id)};
 var clamp=function(n,a,b){return Math.max(a,Math.min(b,n))};
 function secure32(){if(!window.crypto||!window.crypto.getRandomValues)throw new Error('Secure browser randomness is unavailable. Please use a modern browser.');var a=new Uint32Array(1);window.crypto.getRandomValues(a);return a[0]}
 function randInt(min,max){min=Math.ceil(Number(min));max=Math.floor(Number(max));if(!isFinite(min)||!isFinite(max)||max<min)throw new Error('Please enter a valid range.');var span=max-min+1,limit=Math.floor(4294967296/span)*span,v;do{v=secure32()}while(v>=limit);return min+(v%span)}
 function randFloat(){return secure32()/4294967296}
 function pick(a){if(!a||!a.length)throw new Error('There are no choices available.');return a[randInt(0,a.length-1)]}
 function vals(id){var e=$(id);return e?e.value.split(/[\n,]+/).map(function(x){return x.trim()}).filter(Boolean):[]}
 function unique(a){return a.filter(function(v,i){return a.indexOf(v)===i})}
 function shuffle(a){var x=a.slice(),i,j,t;for(i=x.length-1;i>0;i--){j=randInt(0,i);t=x[i];x[i]=x[j];x[j]=t}return x}
 function esc(v){return String(v).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
 function field(label,html){return '<div class="field"><label>'+label+'</label>'+html+'</div>'}
 function resultMain(text){return '<div class="result-main">'+text+'</div>'}
 function safeText(v){return String(v).replace(/[<>]/g,'')}
 function addCopy(container,text){var btn=document.createElement('button');btn.type='button';btn.className='copy-result';btn.textContent='Copy result';btn.onclick=function(){navigator.clipboard&&navigator.clipboard.writeText(text).then(function(){btn.textContent='Copied ✓';setTimeout(function(){btn.textContent='Copy result'},1200)}).catch(function(){btn.textContent='Copy failed'})};container.appendChild(btn)}
 function setOutput(html,text){var out=$('result');out.className='result';out.innerHTML=html;if(text){addCopy(out,text)}}
 function error(msg){var out=$('result');out.className='result error-result';out.textContent=msg||'Something went wrong. Please try again.'}
 function options(arr,id){return '<select id="'+id+'">'+arr.map(function(x){return '<option value="'+esc(x)+'">'+esc(x)+'</option>'}).join('')+'</select>'}
 function textCount(id,def){return Math.max(1,Math.min(5,parseInt($(id).value,10)||def||1))}
 function hslFromRgb(r,g,b){r/=255;g/=255;b/=255;var max=Math.max(r,g,b),min=Math.min(r,g,b),h=0,s,l=(max+min)/2,d=max-min;if(d!==0){s=l>0.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}else{s=0}return {h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)}}
 function rgbFromHex(hex){var n=parseInt(hex.slice(1),16);return {r:(n>>16)&255,g:(n>>8)&255,b:n&255}}
 function randomHex(){return '#'+randInt(0,0xFFFFFF).toString(16).toUpperCase().padStart(6,'0')}
 function setCopyCode(el,txt){el.onclick=function(){if(navigator.clipboard){navigator.clipboard.writeText(txt);el.textContent='Copied ✓';setTimeout(function(){el.textContent=txt},1200)}}}
 function normalizeTheme(s){return s.toLowerCase().replace(/[^a-z0-9\s&-]/g,' ').replace(/\s+/g,' ').trim()}
 function themeWords(input){var t=normalizeTheme(input||'');var keys=Object.keys(D.themes||{}),found=[];keys.forEach(function(k){if(t.indexOf(k)>=0)found=found.concat(D.themes[k])});var tokens=t.split(' ').filter(function(x){return x.length>1});if(found.length)return unique(found.concat(tokens));return tokens.length?unique(tokens):D.themes.gaming||['Nova','Pixel','Turbo']}
 var STATE={coin:{count:0,history:[]},yes:[],wheel:{rotation:0,spinning:false},noRepeat:{}}
 function regionNames(){var v=$('nameRegion').value;return D.names[v]||D.names.Global||[]}
 function themeOptionHtml(){return ['Gaming','Football','Space','Nature','Music','Anime','Tech','Cars','Luxury','Cute','Fantasy','Dark','Travel','Food'].map(function(x){return '<option>'+x+'</option>'}).join('')}
 function weightedThemeParts(theme){var low=normalizeTheme(theme);var vocab=themeWords(low);var userTokens=low.split(' ').filter(function(x){return x.length>1});var left=userTokens.length?pick(userTokens):pick(vocab);var right=pick(vocab);if(right.toLowerCase()===String(left).toLowerCase()&&vocab.length>1)right=pick(vocab);return [left,right]}
 function makeUsernames(theme,style,separator,withNumber){var pairs=[],low=normalizeTheme(theme),styleWords={clean:['Pro','Prime','Wave','Core','Edge','Flow','Link'],short:['X','HQ','Go','Lab','One','Plus'],funny:['Biscuit','Banana','Potato','Pickle','Waffle','Noodle','Goofy','Silly'],cool:['Ace','Rogue','Nova','Vibe','Elite','Prime','Flux'],gaming:['Clutch','Apex','Pixel','Turbo','Quest','Strike'],aesthetic:['Velvet','Luna','Bloom','Muse','Cloud','Satin']};var styleList=styleWords[style.toLowerCase()]||styleWords.clean;for(var i=0;i<20&&pairs.length<20;i++){var p=weightedThemeParts(low);var sep=separator==='None'?'':separator;var n=withNumber?String(randInt(1,999)):'';var extra=pick(styleList);var name=(p[0]+sep+p[1]+sep+extra+n).replace(/\s+/g,'');if(pairs.indexOf(name)<0)pairs.push(name)}return pairs}
 function generateTeamNames(style,keyword,count){var maps={Powerful:['Titans','Warriors','Legends','Giants','Champions','Guardians','Raiders'],Funny:['Bananas','Waffles','Potatoes','Goofballs','Pickles','Couch Crew','Chaos Club'],Esports:['Vortex','Phantoms','Reapers','Strikers','Rivals','Nexus','Dynasty'],Sports:['United','Rovers','Athletic','City','Rangers','Wanderers','FC'],Fantasy:['Dragons','Knights','Ravens','Wolves','Guardians','Fireborn','Moonblades'],School:['Scholars','Aces','All-Stars','House','Crew','Classics','Trailblazers'],Casual:['Friends','Crew','Squad','Gang','Collective','Club','Team']};var bases=maps[style]||maps.Powerful;var out=[];for(var i=0;i<count;i++){var word=keyword?pick([keyword,keyword+' '+pick(bases)]):pick(bases);var lead=pick(['The','Team','Club','House','Squad']);var name=keyword?word:lead+' '+word;if(out.indexOf(name)<0)out.push(name)}return out}
 function generateFantasy(style,count){var maps={Royal:['Crown','Kingdom','Throne','Court','Majesty'],Dark:['Shadow','Night','Dread','Raven','Void'],Nature:['Oak','Willow','Fern','River','Bloom'],Warrior:['Blade','Shield','Valor','Storm','Iron'],Arcane:['Rune','Mystic','Spell','Arcana','Crystal'],Celestial:['Star','Moon','Solar','Nova','Eclipse'],Pirate:['Black','Tide','Skull','Corsair','Reef'],Dragon:['Drake','Wyvern','Ember','Scale','Flame']};var v=maps[style]||maps.Arcane,out=[];for(var i=0;i<count;i++){var n=pick(D.fantasyFirst)+' '+pick(D.fantasyLast)+' · '+pick(v);if(out.indexOf(n)<0)out.push(n)}return out}
 function generatePet(vibe,count){var maps={Cute:['Mochi','Peaches','Bubbles','Honey','Poppy','Cookie'],Funny:['Pickle','Noodle','Waffle','Biscuit','Potato','Socks'],Elegant:['Pearl','Jasper','Cleo','Dahlia','Velvet','Opal'],Food:['Muffin','Taco','Mango','Brownie','Toast','Pepper'],Nature:['Willow','Maple','River','Hazel','Clover','Fern'],Mythic:['Phoenix','Atlas','Loki','Freya','Apollo','Athena'],Cool:['Onyx','Storm','Diesel','Shadow','Blaze','Rogue'],Tiny:['Pip','Dot','Bean','Peanut','Pipkin','Button']};var v=maps[vibe]||maps.Cute,out=[];for(var i=0;i<count;i++){var n=pick(v);if(randInt(0,1))n+=' '+pick(D.petSecond);if(out.indexOf(n)<0)out.push(n)}return out}
 function drawWheel(canvas,items,angle){var ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1,w=canvas.clientWidth||520,h=w;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);var cx=w/2,cy=h/2,r=Math.min(w,h)/2-12,slice=2*Math.PI/items.length;ctx.save();ctx.translate(cx,cy);ctx.rotate(angle*Math.PI/180);for(var i=0;i<items.length;i++){var a=-Math.PI/2+i*slice,b=a+slice;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,b);ctx.closePath();ctx.fillStyle=['#6b57f1','#ff5f98','#14b8a6','#f59e0b','#06b6d4','#8b5cf6','#ef4444','#22c55e','#3b82f6','#ec4899','#84cc16','#f97316'][i%12];ctx.fill();ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.rotate(a+slice/2);ctx.fillStyle='#fff';ctx.font=(items.length>12?'12px':'15px')+' Inter,Arial,sans-serif';ctx.fontWeight='800';ctx.textAlign='right';ctx.textBaseline='middle';var label=items[i].length>19?items[i].slice(0,18)+'…':items[i];ctx.fillText(label,r-18,0);ctx.restore()}ctx.restore()}
 function renderTool(tool){var title=$('tool-title'),desc=$('tool-desc'),controls=$('controls'),run=$('run');if(!tool||!title||!desc||!controls||!run)return;title.textContent=tool.title;desc.textContent=tool.desc;controls.innerHTML=tool.render();run.textContent=tool.button||'Generate';if(tool.afterRender)tool.afterRender();run.onclick=function(){if(run.disabled)return;try{if(tool.beforeRun&&tool.beforeRun()===false)return;var res=tool.run();if(res&&res.html)setOutput(res.html,res.text);else if(typeof res==='string')setOutput(res,typeof res==='string'?res.replace(/<[^>]+>/g,''):null);if(tool.afterRun)tool.afterRun(res)}catch(e){error(e&&e.message?e.message:'Something went wrong. Please try again.')}}}
 function setOutput(html,text){var out=$('result');out.className='result';out.innerHTML=html;if(text){var b=document.createElement('button');b.type='button';b.className='copy-result';b.textContent='Copy result';b.onclick=function(){if(navigator.clipboard){navigator.clipboard.writeText(text).then(function(){b.textContent='Copied ✓';setTimeout(function(){b.textContent='Copy result'},1200)})}};out.appendChild(b)}}
 var tools={
  randomNumber:{title:'Random Number Generator',desc:'Pick a fresh random number every time.',button:'Generate number',render:function(){return field('Mode',options(['Whole number','Decimal'],'numberMode'))+field('Minimum','<input id="min" type="number" value="1">')+field('Maximum','<input id="max" type="number" value="100">')+field('Decimal places','<select id="decimals"><option>1</option><option selected>2</option><option>3</option><option>4</option></select>')},run:function(){var min=Number($('min').value),max=Number($('max').value);if(max<min)throw new Error('Maximum must be at least the minimum.');if($('numberMode').value==='Whole number')return resultMain(String(randInt(min,max)));var p=Number($('decimals').value)||2;return resultMain((min+randFloat()*(max-min)).toFixed(p))}},
  coinFlip:{title:'Coin Flip',desc:'Genuinely random heads or tails — repeats are possible.',button:'🪙 Flip the coin',render:function(){return '<div class="stats-row"><span id="flipCount">0 / 12 flips this session</span><span id="flipSummary">Heads 0 · Tails 0</span></div><p class="control-help">The result is independently random on every press. It will not alternate on purpose.</p><button type="button" class="secondary-action" id="resetFlips">Reset session</button>'},beforeRun:function(){if(STATE.coin.count>=12){error('You have reached 12 flips for this session. Reset to flip again.');return false}return true},run:function(){var h=randInt(0,1)===0?'Heads':'Tails';STATE.coin.count++;STATE.coin.history.push(h);return resultMain(h==='Heads'?'Heads 🪙':'Tails 🪙')},afterRun:function(){var h=STATE.coin.history.filter(function(x){return x==='Heads'}).length,t=STATE.coin.count-h;$('flipCount').textContent=STATE.coin.count+' / 12 flips this session';$('flipSummary').textContent='Heads '+h+' · Tails '+t;if(STATE.coin.count>=12)$('run').disabled=true}},
  diceRoller:{title:'Dice Roller',desc:'Choose dice type and roll up to 20 at once.',button:'🎲 Roll dice',render:function(){return field('Number of dice','<input id="count" type="number" value="1" min="1" max="20">')+field('Sides',options(['4','6','8','10','12','20','100'],'sides'))},run:function(){var n=clamp(parseInt($('count').value,10)||1,1,20),s=Number($('sides').value),r=[],t=0;for(var i=0;i<n;i++){var x=randInt(1,s);r.push(x);t+=x}return resultMain(r.join(' · ')+'<small>Total: '+t+'</small>')}},
  randomPicker:{title:'Random Picker',desc:'Paste your own choices and let chance pick one.',button:'🎲 Pick one',render:function(){return field('Choices','<textarea id="items" rows="9" placeholder="Pizza\nBurger\nPasta\nCurry"></textarea>')+field('Avoid repeats', '<label class="check-row"><input id="avoidRepeat" type="checkbox"> Do not repeat until the list is exhausted</label>')},run:function(){var a=unique(vals('items'));if(!a.length)throw new Error('Add at least one choice.');var key=a.join('|');var used=STATE.noRepeat[key]||[];if($('avoidRepeat').checked&&used.length>=a.length){used=[]}var choices=$('avoidRepeat').checked?a.filter(function(x){return used.indexOf(x)<0}):a;var w=pick(choices);if($('avoidRepeat').checked){used.push(w);STATE.noRepeat[key]=used}return resultMain(esc(w))}},
  wheelSpinner:{title:'Wheel Spinner',desc:'A real animated wheel that spins to your randomly selected winner.',button:'🎡 Spin the wheel',render:function(){return '<div class="wheel-shell"><div class="wheel-pointer" aria-hidden="true"></div><canvas id="wheelCanvas" class="wheel-canvas"></canvas></div>'+field('Wheel entries','<textarea id="items" rows="9" placeholder="Pizza\nBurger\nPasta\nCurry">Pizza\nBurger\nPasta\nCurry</textarea>')+'<label class="check-row"><input id="removeWinner" type="checkbox"> Remove the winner after each spin</label><p class="control-help">Change the entries and the wheel redraws automatically. The pointer stays fixed while the wheel physically rotates.</p>'},afterRender:function(){var c=$('wheelCanvas'),ta=$('items');function sync(){var a=unique(vals('items'));if(!a.length)a=['Add entries'];drawWheel(c,a,STATE.wheel.rotation)}ta.addEventListener('input',sync);sync();window.addEventListener('resize',sync)},run:function(){var c=$('wheelCanvas'),a=unique(vals('items'));if(!a.length)throw new Error('Add at least one entry.');if(a.length===1)throw new Error('Add at least two entries for a wheel.');if(STATE.wheel.spinning)throw new Error('The wheel is already spinning.');var winnerIndex=randInt(0,a.length-1),slice=360/a.length,center=winnerIndex*slice+slice/2,current=STATE.wheel.rotation%360,delta=((360-center-current)+360)%360+360*5+randInt(0,2)*360,target=STATE.wheel.rotation+delta;STATE.wheel.spinning=true;c.style.transform='rotate('+target+'deg)';var resultText=a[winnerIndex];setTimeout(function(){STATE.wheel.rotation=target%360;STATE.wheel.spinning=false;drawWheel(c,a,STATE.wheel.rotation);setOutput(resultMain('🎡 '+esc(resultText)),resultText);if($('removeWinner').checked){var remaining=a.filter(function(_,i){return i!==winnerIndex});$('items').value=remaining.join('\n');drawWheel(c,remaining.length?remaining:['Add entries'],STATE.wheel.rotation)}},1700);return ''}},
  randomName:{title:'Random Name Generator',desc:'Explore a much larger, globally diverse name library.',button:'👤 Generate name',render:function(){return field('Region / style',options(Object.keys(D.names||{}),'nameRegion'))+field('Number of names','<input id="count" type="number" value="1" min="1" max="5">')},run:function(){var a=D.names[$('nameRegion').value]||D.names.Global,n=textCount('count',1),o=[];while(o.length<n){var x=pick(a);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}},
  randomWord:{title:'Random Word Generator',desc:'Hundreds of everyday words with much less repetition.',button:'🔤 Generate word',render:function(){return field('Category',options(['Any','Nature','Creative','Positive','Travel','Objects','Feelings'],'wordCategory'))+field('Number of words','<input id="count" type="number" value="1" min="1" max="8">')},run:function(){var category=$('wordCategory').value,a=D.words,n=textCount('count',1);var pools={Nature:['forest','ocean','river','meadow','wildflower','sunrise','rainbow','thunder','breeze','garden','mountain','valley','island','sunset','rain','cloud','leaf','stone','willow','moonlight','canyon','cliff','stream','cedar','fern','orchid'],Creative:['canvas','melody','sketch','poem','rhythm','novel','design','colour','story','idea','spark','imagine','create','invent','wonder','camera','piano','guitar','theatre','script'],Positive:['kindness','courage','joy','hope','smile','gratitude','friendship','success','calm','bright','brave','trust','respect','laugh','dream','freedom','peace','confidence'],Travel:['passport','journey','voyage','airport','compass','map','island','harbour','ticket','train','hotel','beach','mountain','road','suitcase'],Objects:['mirror','button','clock','hammer','key','ladder','machine','needle','paper','pencil','pocket','ribbon','robot','suitcase','umbrella','window','camera','medal'],Feelings:['joy','hope','wonder','curiosity','calm','confidence','excitement','surprise','friendship','trust','gratitude','bravery','patience','peace','laughter']};if(category!=='Any')a=(pools[category]||a);var o=[];while(o.length<n){var x=pick(a);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join(' · '))}},
  randomCountry:{title:'Random Country Generator',desc:'Choose from almost every country, with regional filters.',button:'🌍 Pick a country',render:function(){return field('Region',options(['Worldwide','Europe','Asia','Africa','Americas','Oceania'],'countryRegion'))},run:function(){var r=$('countryRegion').value,a=r==='Worldwide'?D.countries:D.countriesByRegion[r];return resultMain('🌍 '+esc(pick(a)))}},
  randomColour:{title:'Random Colour Generator',desc:'Generate a colour with correct HEX, RGB and HSL values.',button:'🎨 Pick a colour',render:function(){return '<p class="control-help">All three formats below represent the same colour.</p>'},run:function(){var hex=randomHex(),rgb=rgbFromHex(hex),hsl=hslFromRgb(rgb.r,rgb.g,rgb.b);var html='<div class="colour-result"><i style="background:'+hex+'"></i><div class="colour-code-grid"><button type="button" class="code-chip" data-code="'+hex+'"><b>HEX</b><span>'+hex+'</span></button><button type="button" class="code-chip" data-code="rgb('+rgb.r+', '+rgb.g+', '+rgb.b+')"><b>RGB</b><span>rgb('+rgb.r+', '+rgb.g+', '+rgb.b+')</span></button><button type="button" class="code-chip" data-code="hsl('+hsl.h+', '+hsl.s+'%, '+hsl.l+'%)"><b>HSL</b><span>hsl('+hsl.h+', '+hsl.s+'%, '+hsl.l+'%)</span></button></div></div>';return {html:html,text:hex+' | rgb('+rgb.r+', '+rgb.g+', '+rgb.b+') | hsl('+hsl.h+', '+hsl.s+'%, '+hsl.l+'%)'}} ,afterRun:function(){document.querySelectorAll('.code-chip').forEach(function(b){b.onclick=function(){var t=b.getAttribute('data-code');if(navigator.clipboard){navigator.clipboard.writeText(t);var old=b.querySelector('span').textContent;b.querySelector('span').textContent='Copied ✓';setTimeout(function(){b.querySelector('span').textContent=old},1000)}}})}},
  randomTeam:{title:'Random Team Generator',desc:'Split names into balanced random teams.',button:'👥 Make teams',render:function(){return field('Names','<textarea id="items" rows="9" placeholder="Alex\nSam\nJamie\nTaylor\nJordan\nCasey"></textarea>')+field('Number of teams','<input id="teams" type="number" value="2" min="2" max="10">')},run:function(){var a=unique(vals('items')),t=clamp(parseInt($('teams').value,10)||2,2,10);if(a.length<t)throw new Error('Add at least as many names as teams.');a=shuffle(a);var groups=Array.from({length:t},function(){return[]});a.forEach(function(x,i){groups[i%t].push(x)});return groups.map(function(g,i){return '<div class="team-block"><strong>Team '+(i+1)+'</strong><span>'+g.map(esc).join(', ')+'</span></div>'}).join('')}},
  whoGoesFirst:{title:'Who Goes First?',desc:'Choose a first player fairly.',button:'🏁 Pick first player',render:function(){return field('Names','<textarea id="items" rows="7" placeholder="Alex\nSam\nJamie"></textarea>')},run:function(){var a=unique(vals('items'));if(!a.length)throw new Error('Add some names first.');return resultMain('🏁 '+esc(pick(a)))}},
  yesOrNo:{title:'Yes or No',desc:'Every answer is an independent random draw — no forced alternation.',button:'✅ Decide',render:function(){return field('Question (optional)','<input id="question" type="text" placeholder="Should I order pizza?">')+'<div class="stats-row"><span id="yesNoStats">Session: 0 answers</span></div>'},run:function(){var ans=randInt(0,1)?'Yes':'No';STATE.yes.push(ans);return resultMain(ans==='Yes'?'Yes ✅':'No ❌')},afterRun:function(){$('yesNoStats').textContent='Session: '+STATE.yes.length+' answers · Yes '+STATE.yes.filter(function(x){return x==='Yes'}).length+' · No '+STATE.yes.filter(function(x){return x==='No'}).length}},
  randomMovie:{title:'Random Movie Picker',desc:'A much larger curated movie library with genre filtering.',button:'🎬 Pick a movie',render:function(){return field('Genre',options(Object.keys(D.movies),'movieGenre'))+field('Number of suggestions','<input id="count" type="number" value="1" min="1" max="5">')},run:function(){var a=D.movies[$('movieGenre').value]||D.movies.Any,n=textCount('count',1),o=[];while(o.length<n){var x=pick(a);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}},
  randomMeal:{title:'Random Meal Generator',desc:'A much larger food library with cuisine and diet filters.',button:'🍽️ Pick a meal',render:function(){return field('Style',options(Object.keys(D.meals),'mealType'))+field('Number of ideas','<input id="count" type="number" value="1" min="1" max="5">')},run:function(){var a=D.meals[$('mealType').value]||D.meals.Any,n=textCount('count',1),o=[];while(o.length<n){var x=pick(a);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}},
  randomChallenge:{title:'Random Challenge Generator',desc:'A much larger list of quick, creative, social and productivity challenges.',button:'🔥 Give me a challenge',render:function(){return field('Type',options(Object.keys(D.challenges),'challengeType'))+field('Number of challenges','<input id="count" type="number" value="1" min="1" max="5">')},run:function(){var a=D.challenges[$('challengeType').value]||D.challenges.Any,n=textCount('count',1),o=[];while(o.length<n){var x=pick(a);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}},
  randomGame:{title:'Random Game Picker',desc:'A huge collection of party, board, word and group games.',button:'🎮 Pick a game',render:function(){return field('Number of games','<input id="count" type="number" value="1" min="1" max="5">')},run:function(){var n=textCount('count',1),o=[];while(o.length<n){var x=pick(D.games);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}},
  randomDate:{title:'Random Date Generator',desc:'Generate a random date inside your chosen range.',button:'📅 Pick a date',render:function(){return '<div class="date-grid"><div class="field"><label>From</label><input id="from" type="date"></div><div class="field"><label>To</label><input id="to" type="date"></div></div>'},run:function(){var f=$('from'),t=$('to'),now=new Date();if(!f.value)f.value=now.toISOString().slice(0,10);if(!t.value){var d=new Date(now);d.setFullYear(d.getFullYear()+1);t.value=d.toISOString().slice(0,10)}var a=new Date(f.value+'T12:00:00'),b=new Date(t.value+'T12:00:00'),days=Math.floor((b-a)/86400000);if(days<0)throw new Error('The To date must be on or after the From date.');return resultMain(new Date(a.getTime()+randInt(0,days)*86400000).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}))}},
  usernameGenerator:{title:'Username Generator',desc:'Type any theme and the generator actually uses it in the username.',button:'✨ Generate usernames',render:function(){return field('Your theme','<input id="theme" type="text" placeholder="football, space, vintage cars, cats...">')+field('Style',options(['Clean','Short','Funny','Cool','Gaming','Aesthetic'],'userStyle'))+field('Separator',options(['None','_','-','.'],'separator'))+field('Include numbers','<label class="check-row"><input id="withNumber" type="checkbox" checked> Add a number</label>')+field('Number of ideas','<input id="count" type="number" value="5" min="1" max="10">')},run:function(){var theme=$('theme').value.trim();if(!theme)throw new Error('Write a theme first.');var style=$('userStyle').value,sep=$('separator').value,n=textCount('count',5),o=makeUsernames(theme,style,sep,$('withNumber').checked);return resultMain(o.slice(0,n).map(esc).join('<small></small>'))}},
  gamerNameGenerator:{title:'Gamer Name Generator',desc:'Style-aware gaming names that actually match the vibe you choose.',button:'🎮 Generate gamer names',render:function(){return field('Style',options(['Stealth','Competitive','Funny','Fantasy','Tech','Toxic','Sniper','Speed','SciFi'],'gamerStyle'))+field('Number of names','<input id="count" type="number" value="5" min="1" max="10">')},run:function(){var maps={Stealth:['Shadow','Silent','Ghost','Night','Wraith'],Competitive:['Clutch','Apex','Elite','Rival','Victory'],Funny:['Banana','Potato','Waffle','Pickle','Goofy'],Fantasy:['Dragon','Rune','Wizard','Mystic','Raven'],Tech:['Byte','Quantum','Cyber','Kernel','Vector'],Toxic:['Venom','Rage','Savage','Fury','Chaos'],Sniper:['Scope','Marksman','Deadeye','Falcon','Viper'],Speed:['Turbo','Velocity','Nitro','Rapid','Blitz'],SciFi:['Cosmic','Nova','Orbit','Nebula','Stellar']};var suffix={Stealth:['Wraith','Shade','Ghost','Hunter','Shadow'],Competitive:['Ace','Prime','Pro','GG','MVP'],Funny:['Potato','Biscuit','Waffle','Noodle','Goof'],Fantasy:['Drake','Mage','Knight','Fae','Dragon'],Tech:['X','Core','OS','AI','Node'],Toxic:['X','Rage','404','Killer','Storm'],Sniper:['Shot','Aim','Scope','OneTap','Hawk'],Speed:['Rush','Dash','Boost','Flash','Bolt'],SciFi:['X','Prime','Zero','Pilot','Drift']};var a=maps[$('gamerStyle').value]||maps.Stealth,s=suffix[$('gamerStyle').value]||suffix.Stealth,n=textCount('count',5),o=[];while(o.length<n){var name=pick(a)+pick(s)+randInt(0,99);if(o.indexOf(name)<0)o.push(name)}return resultMain(o.map(esc).join('<small></small>'))}},
  teamNameGenerator:{title:'Team Name Generator',desc:'More styles, more formats, and optional keywords.',button:'🏆 Generate team names',render:function(){return field('Style',options(['Powerful','Funny','Esports','Sports','Fantasy','School','Casual'],'teamStyle'))+field('Optional keyword','<input id="keyword" type="text" placeholder="your town, colour, animal...">')+field('Number of names','<input id="count" type="number" value="5" min="1" max="10">')},run:function(){return resultMain(generateTeamNames($('teamStyle').value,$('keyword').value.trim(),textCount('count',5)).map(esc).join('<small></small>'))}},
  fantasyNameGenerator:{title:'Fantasy Name Generator',desc:'Names that match the fantasy style you choose.',button:'🧙 Generate fantasy names',render:function(){return field('Style',options(['Royal','Dark','Nature','Warrior','Arcane','Celestial','Pirate','Dragon'],'fantasyStyle'))+field('Number of names','<input id="count" type="number" value="5" min="1" max="10">')},run:function(){return resultMain(generateFantasy($('fantasyStyle').value,textCount('count',5)).map(esc).join('<small></small>'))}},
  petNameGenerator:{title:'Pet Name Generator',desc:'Pet names chosen to match the vibe you want.',button:'🐾 Generate pet names',render:function(){return field('Vibe',options(['Cute','Funny','Elegant','Food','Nature','Mythic','Cool','Tiny'],'petVibe'))+field('Number of names','<input id="count" type="number" value="5" min="1" max="10">')},run:function(){return resultMain(generatePet($('petVibe').value,textCount('count',5)).map(esc).join('<small></small>'))}},
  partyGameGenerator:{title:'Party Game Generator',desc:'Pick something fun for a group.',button:'🎉 Pick party games',render:function(){return field('Number of games','<input id="count" type="number" value="3" min="1" max="8">')},run:function(){var n=textCount('count',3),o=[];while(o.length<n){var x=pick(D.games);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}},
  couplesDecisionMaker:{title:'Couples Decision Maker',desc:'Let RandoSpino settle the little things.',button:'❤️ Decide for us',render:function(){return field('Option A','<input id="a" type="text" placeholder="Movie night">')+field('Option B','<input id="b" type="text" placeholder="Dinner out">')},run:function(){var a=safeText($('a').value.trim()),b=safeText($('b').value.trim());if(!a||!b)throw new Error('Enter both options first.');return resultMain('❤️ '+esc(pick([a,b]))) }},
  secretSantaPicker:{title:'Secret Santa Picker',desc:'A proper no-self-draw Secret Santa assignment.',button:'🎁 Make the draw',render:function(){return field('Names','<textarea id="items" rows="10" placeholder="Alex\nSam\nJamie\nTaylor"></textarea>')},run:function(){var a=unique(vals('items'));if(a.length<2)throw new Error('Add at least two different names.');var target,tries=0;do{target=shuffle(a);tries++}while(target.some(function(x,i){return x===a[i]})&&tries<1000);if(target.some(function(x,i){return x===a[i]}))throw new Error('Could not create a valid draw. Try again.');return a.map(function(x,i){return '<div class="team-block"><strong>'+esc(x)+'</strong><span>→ '+esc(target[i])+'</span></div>'}).join('')}},
  animals:{title:'Random Animal Generator',desc:'Pick from a large animal library.',button:'🐾 Pick an animal',render:function(){return field('Number of animals','<input id="count" type="number" value="3" min="1" max="10">')},run:function(){var n=textCount('count',3),o=[];while(o.length<n){var x=pick(D.animals);if(o.indexOf(x)<0)o.push(x)}return resultMain(o.map(esc).join('<small></small>'))}}
 };
 function adaptLinks(){if(location.hostname.indexOf('github.io')<0||location.pathname.indexOf('/randospino')!==0)return;document.querySelectorAll('a[href^="/"]').forEach(function(a){var h=a.getAttribute('href');if(h&&h.indexOf('/randospino')!==0)a.setAttribute('href','/randospino'+h)})}
 adaptLinks();var key=document.body.getAttribute('data-tool');renderTool(tools[key]);
 var reset=$('resetFlips');if(reset)reset.onclick=function(){STATE.coin={count:0,history:[]};$('flipCount').textContent='0 / 12 flips this session';$('flipSummary').textContent='Heads 0 · Tails 0';$('run').disabled=false;$('result').innerHTML='<strong>Ready when you are.</strong>'};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){loadData(init)});else loadData(init);
})();
