(function(){
  'use strict';
  var FAV='randospino:favourites:v5', RECENT='randospino:recent:v5', USES='randospino:uses:v5';
  var TOOLS=[
    ['Random Number','./random-number/','Pick any number from a custom range.'],['Coin Flip','./coin-flip/','Genuinely random heads or tails.'],['Dice Roller','./dice-roller/','Roll dice with different sides.'],['Random Name','./random-name/','Generate names from diverse pools.'],['Random Word','./random-word/','Generate one or many words.'],['Random Country','./random-country/','Generate a country from a broad global list.'],['Random Colour','./random-colour/','Generate a colour with HEX, RGB and HSL.'],['Random Team','./random-team/','Split names into random teams.'],
    ['Random Letter','./random-letter/','Pick a random A–Z letter.'],['Random Lowercase Letter','./random-lowercase-letter/','Pick a random lowercase letter.'],['Random Emoji','./random-emoji/','Get a surprise emoji.'],['Random Month','./random-month/','Pick a random month.'],['Random Day','./random-day/','Pick a random day.'],['Random Zodiac Sign','./random-zodiac-sign/','Choose a zodiac sign.'],['Random Pokémon','./random-pokemon/','Pick a Pokémon at random.'],['Random Superpower','./random-superpower/','Discover a random superpower.'],['Random Drawing Prompt','./random-drawing-prompt/','Get a fresh idea to draw.'],['Random Writing Prompt','./random-writing-prompt/','Get a creative writing idea.'],['Random Workout','./random-workout/','Get a random workout idea.'],['Random Date Idea','./random-date-idea/','Choose a date idea.'],['Random Holiday Destination','./random-holiday-destination/','Choose somewhere to travel.'],['Random Food Ingredient','./random-food-ingredient/','Pick an ingredient to inspire a dish.'],['Random Colour Name','./random-colour-name/','Pick a colour name.'],['Random Colour HEX','./random-colour-hex/','Pick a colour HEX value.'],['Random Shape','./random-shape/','Pick a shape.'],['Random Season','./random-season/','Pick a season.'],['Random Continent','./random-continent/','Pick a continent.'],['Random Sport','./random-sport/','Pick a sport.'],['Random Animal','./random-animal/','Pick an animal.'],['Random Object','./random-object/','Pick an everyday object.'],['Random Quote','./random-quote/','Get an original short quote.'],['Random Keyboard Key','./random-keyboard-key/','Pick a keyboard key.'],['Random Yes or No Question','./random-yes-or-no-question/','Get a playful yes-or-no prompt.'],
    ['Random Picker','./random-picker/','Pick from your own list.'],['Wheel Spinner','./wheel-spinner/','Spin a real visual wheel.'],['Who Goes First?','./who-goes-first/','Choose a first player fairly.'],['Yes or No','./yes-or-no/','Get a genuinely random yes or no.'],['Random Movie','./random-movie/','Pick a movie by genre.'],['Random Meal','./random-meal/','Choose a meal by type or cuisine.'],['Random Challenge','./random-challenge/','Generate a challenge to try.'],['Random Game','./random-game/','Pick a game for your group.'],['Random Date','./random-date/','Choose a random date in a range.'],
    ['Username Generator','./username-generator/','Create theme-aware usernames.'],['Gamer Name Generator','./gamer-name-generator/','Generate style-based gamer names.'],['Team Name Generator','./team-name-generator/','Create team names by vibe.'],['Fantasy Name Generator','./fantasy-name-generator/','Create fantasy names by style.'],['Pet Name Generator','./pet-name-generator/','Find pet names by vibe.'],['Party Game Generator','./party-game-generator/','Choose a game everyone can play.'],['Secret Santa Picker','./secret-santa-picker/','Make a fair Secret Santa draw.'],['Couples Decision Maker','./couples-decision-maker/','Settle two-option decisions.'],
    ['Random Time','./random-time/','Pick a random time of day.'],['Random Year','./random-year/','Choose a random year.'],['Random Language','./random-language/','Pick a language at random.'],['Random Currency','./random-currency/','Pick a currency at random.'],['Random School Subject','./random-school-subject/','Pick a school subject.'],['Random Job','./random-job/','Discover a random job.'],['Random Board Game','./random-board-game/','Choose a board game to play.'],['Random Playing Card','./random-playing-card/','Draw a random playing card.'],['Random Truth or Dare','./random-truth-or-dare/','Get a ready-to-use prompt.'],['Random Would You Rather','./random-would-you-rather/','Get a would-you-rather question.'],['Random Charades','./random-charades/','Get a charades idea.'],['Random Snack','./random-snack/','Let chance choose your snack.'],['Random Breakfast','./random-breakfast/','Pick a breakfast idea.'],['Random Dessert','./random-dessert/','Choose a dessert.'],['Random Restaurant Cuisine','./random-restaurant-cuisine/','Choose a cuisine.'],['Random Birthstone','./random-birthstone/','Pick a birthstone at random.'],['Random Planet','./random-planet/','Pick a planet.'],['Random Chemical Element','./random-element/','Pick a chemical element.'],['Random Historical Era','./random-era/','Choose an era.'],['Random Activity','./random-activity/','Get a creative activity.'],['Random Classroom Choice','./random-classroom-choice/','Pick a classroom option fairly.']
  ];
  var CATS={Random:['number','flip','dice','letter','word','country','colour','emoji','month','day','zodiac','pokemon','planet','element','animal','object','quote','keyboard','year','language','currency','time','birthstone','season','continent','sport','superpower'],Decide:['picker','wheel','first','yes or no','couples','challenge','movie','meal','date'],Games:['game','gamer','board game','playing card','charades','party'],Generate:['generator','name','prompt','team','fantasy','pet','username','writing','drawing'],Food:['meal','food','ingredient','snack','breakfast','dessert','cuisine'],School:['school','classroom','subject'],Travel:['country','continent','destination'],Creative:['drawing','writing','prompt','activity','fantasy'],Party:['party','truth or dare','would you rather','charades']};
  var popular=['./wheel-spinner/','./random-game/','./random-name/','./random-number/','./random-meal/','./random-picker/','./gamer-name-generator/','./random-challenge/'];
  function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch(e){return f;}}
  function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}
  function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function find(url){return TOOLS.find(function(t){return t[1]===url;});}
  function icon(n){n=n.toLowerCase();if(n.indexOf('game')>-1||n.indexOf('gamer')>-1)return'🎮';if(n.indexOf('name')>-1)return'✨';if(/food|meal|snack|breakfast|dessert|cuisine/.test(n))return'🍴';if(/country|continent|destination|planet/.test(n))return'🌍';if(/colour|color|hex/.test(n))return'🎨';if(n.indexOf('wheel')>-1)return'🎡';if(n.indexOf('movie')>-1)return'🎬';if(/word|letter|language/.test(n))return'🔤';if(/workout|sport/.test(n))return'💪';if(/school|classroom|subject/.test(n))return'📚';if(/decision|yes or no|picker|first/.test(n))return'✅';if(/date|time|year|month|day/.test(n))return'📅';if(/number|dice/.test(n))return'🎲';if(/animal|pet/.test(n))return'🐾';if(/writing|drawing|prompt|creative|activity/.test(n))return'💡';return'✦';}
  function secure(max){if(window.crypto&&window.crypto.getRandomValues){var a=new Uint32Array(1),span=max+1,lim=Math.floor(4294967296/span)*span,v;do{window.crypto.getRandomValues(a);v=a[0];}while(v>=lim);return v%span;}return Math.floor(Math.random()*(max+1));}
  function catsFor(t){var n=(t[0]+' '+t[2]).toLowerCase(),out=[];Object.keys(CATS).forEach(function(k){if(CATS[k].some(function(w){return n.indexOf(w)>-1;}))out.push(k);});return out.length?out:['Random'];}
  function card(t,extra){return'<a class="v6-card '+(extra||'')+'" href="'+t[1]+'" data-url="'+t[1]+'"><div class="v6-card-icon">'+icon(t[0])+'</div><div class="v6-card-copy"><b>'+esc(t[0])+'</b><small>'+esc(t[2])+'</small></div><span class="v6-arrow">→</span></a>';}
  function directoryCard(t){var fav=read(FAV,[]).indexOf(t[1])>-1;return'<a class="tool-card v3-card" href="'+t[1]+'" data-url="'+t[1]+'"><span class="v3-card-top"><b>'+esc(t[0])+'</b><button type="button" class="fav-btn '+(fav?'is-fav':'')+'" data-fav="'+t[1]+'" aria-label="'+(fav?'Remove from favourites':'Add to favourites')+'">'+(fav?'★':'☆')+'</button></span><span>'+esc(t[2])+'</span></a>';}
  function markUse(url){var uses=read(USES,{});uses[url]=(uses[url]||0)+1;write(USES,uses);var r=read(RECENT,[]).filter(function(x){return x!==url;});r.unshift(url);write(RECENT,r.slice(0,12));}
  function toggleFavourite(url){var f=read(FAV,[]),i=f.indexOf(url);if(i>-1)f.splice(i,1);else f.unshift(url);write(FAV,f.slice(0,50));renderDirectory();renderUtilities();}
  function setupClicks(root){(root||document).querySelectorAll('.v6-card,.search-result-card,.v3-card,.v3-mini-card').forEach(function(a){if(a.dataset.v6bound)return;a.dataset.v6bound='1';a.addEventListener('click',function(){markUse(a.getAttribute('href'));if(window.RandoSpinoAnalytics)window.RandoSpinoAnalytics.event('tool_click',{tool:a.getAttribute('href')});});});(root||document).querySelectorAll('[data-fav]').forEach(function(b){if(b.dataset.v6fav)return;b.dataset.v6fav='1';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();toggleFavourite(b.getAttribute('data-fav'));});});}
  function renderDirectory(){var dir=document.getElementById('v3-directory');if(!dir)return;dir.innerHTML=TOOLS.map(directoryCard).join('');setupClicks(dir);}
  function renderUtilities(){var host=document.getElementById('v3-tools');if(!host)return;var recent=read(RECENT,[]),fav=read(FAV,[]);function block(items,title,empty){if(!items.length)return'<section class="v3-mini"><div class="v3-mini-head">'+title+'</div><p class="v3-empty">'+empty+'</p></section>';return'<section class="v3-mini"><div class="v3-mini-head">'+title+'</div><div class="v3-mini-grid">'+items.map(function(url){var t=find(url);return t?'<a class="v3-mini-card" href="'+t[1]+'"><span>'+esc(t[0])+'</span><small>'+esc(t[2])+'</small></a>':'';}).join('')+'</div></section>';}
    host.innerHTML=block(recent,'Recently used','Your recent tools will appear here.')+block(fav,'Favourites','Star a tool to keep it here.');setupClicks(host);}
  function renderHomeExtras(){var host=document.querySelector('.v3-discovery');if(!host||document.getElementById('v6-enhanced'))return;var wrap=document.createElement('div');wrap.id='v6-enhanced';wrap.innerHTML='<div class="v6-category-row"><button class="v6-cat is-active" data-cat="All">✨ All</button>'+Object.keys(CATS).map(function(c){return'<button class="v6-cat" data-cat="'+c+'">'+icon(c)+' '+c+'</button>';}).join('')+'</div><section class="v6-popular"><div class="v6-section-head"><div><span class="kicker">POPULAR</span><h3>Popular picks</h3></div><span class="v6-live-dot">● Live on this device</span></div><div class="v6-grid" id="v6-popular-grid"></div></section>';host.appendChild(wrap);var cats=wrap.querySelectorAll('.v6-cat');cats.forEach(function(b){b.addEventListener('click',function(){cats.forEach(function(x){x.classList.remove('is-active');});b.classList.add('is-active');var c=b.dataset.cat;document.querySelectorAll('#v3-directory .v3-card').forEach(function(cardEl){var t=find(cardEl.getAttribute('href'));cardEl.style.display=c==='All'||(t&&catsFor(t).indexOf(c)>-1)?'flex':'none';});});});renderPopular();setupClicks(wrap);}
  function renderPopular(){var g=document.getElementById('v6-popular-grid');if(!g)return;var uses=read(USES,{}),ordered=TOOLS.slice().sort(function(a,b){return(uses[b[1]]||0)-(uses[a[1]]||0);});var top=ordered.filter(function(t){return uses[t[1]];}).slice(0,8);if(top.length<8)top=popular.map(find).filter(Boolean).concat(top).filter(function(t,i,a){return a.indexOf(t)===i;}).slice(0,8);g.innerHTML=top.map(function(t){return card(t);}).join('');setupClicks(g);}
  function enhanceSearch(){var input=document.getElementById('v3-search'),results=document.getElementById('v3-search-results'),count=document.getElementById('v3-search-count');if(!input||!results||input.dataset.v6bound)return;input.dataset.v6bound='1';input.addEventListener('input',function(){var q=input.value.toLowerCase().trim();var synonyms={dinner:['meal','food','snack','breakfast','dessert','cuisine'],football:['sport','team','game'],gaming:['gamer','game','board game','pokemon'],school:['school','classroom','subject'],party:['party','charades','truth or dare','would you rather','game'],holiday:['destination','country','travel'],name:['name','username','gamer','fantasy','pet','team'],creative:['writing','drawing','prompt','activity'],decide:['picker','wheel','yes or no','decision']};var words=[q].concat(synonyms[q]||[]);var matches=q?TOOLS.filter(function(t){var text=(t[0]+' '+t[2]).toLowerCase(),cats=catsFor(t).join(' ').toLowerCase();return words.some(function(w){return text.indexOf(w)>-1||cats.indexOf(w)>-1;});}):[];count.textContent=q?(matches.length+' tool'+(matches.length===1?'':'s')+' found'):'';if(!q){results.innerHTML='';results.classList.remove('has-results');return;}if(!matches.length){results.innerHTML='<div class="search-empty"><span class="search-empty-icon">🔎</span><div><strong>No tools found</strong><small>Try <em>dinner</em>, <em>gaming</em>, <em>school</em>, <em>party</em> or <em>creative</em>.</small></div></div>';results.classList.add('has-results');return;}results.innerHTML='<div class="search-results-heading"><strong>'+matches.length+' '+(matches.length===1?'match':'matches')+'</strong><span>Tap a tool to open it</span></div><div class="search-results-grid">'+matches.map(function(t){return card(t,'search-result-card');}).join('')+'</div>';results.classList.add('has-results');setupClicks(results);});}
  function surprise(){var t=TOOLS[secure(TOOLS.length-1)],overlay=document.createElement('div');overlay.className='v6-surprise';overlay.innerHTML='<div class="v6-surprise-card"><div class="v6-spark">✨</div><span>RandoSpino picked…</span><div class="v6-surprise-name">'+icon(t[0])+' '+esc(t[0])+'</div><small>'+esc(t[2])+'</small><div class="v6-surprise-actions"><a href="'+t[1]+'" class="hero-btn">Open tool →</a><button class="secondary-action" type="button">Pick again</button></div></div>';document.body.appendChild(overlay);overlay.querySelector('.secondary-action').onclick=function(){overlay.remove();setTimeout(surprise,30);};overlay.addEventListener('click',function(e){if(e.target===overlay)overlay.remove();});setTimeout(function(){if(overlay.isConnected)overlay.classList.add('show');},10);}
  function bindSurprise(){document.querySelectorAll('#surpriseBtn,#surpriseBtn2').forEach(function(b){if(b.dataset.v6bound)return;b.dataset.v6bound='1';b.addEventListener('click',surprise);});}
  function bindShare(){var b=document.getElementById('shareSite');if(!b||b.dataset.v6bound)return;b.dataset.v6bound='1';b.onclick=function(){var data={title:'RandoSpino',text:"Can't decide? Let RandoSpino choose.",url:location.href};if(navigator.share)navigator.share(data).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(function(){var old=b.textContent;b.textContent='Link copied ✓';setTimeout(function(){b.textContent=old;},1200);});};}
  function boot(){renderDirectory();renderUtilities();renderHomeExtras();enhanceSearch();bindSurprise();bindShare();setupClicks();setInterval(renderPopular,5000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
