(function(){
  'use strict';
  var FAV_KEY='randospino:favourites:v4', RECENT_KEY='randospino:recent:v4';
  var TOOLS=[
    ['Random Number','./random-number/','Pick any number from a custom range.'],['Coin Flip','./coin-flip/','Genuinely random heads or tails.'],['Dice Roller','./dice-roller/','Roll dice with different sides.'],['Random Name','./random-name/','Generate names from diverse pools.'],['Random Word','./random-word/','Generate one or many words.'],['Random Country','./random-country/','Generate a country from a broad global list.'],['Random Colour','./random-colour/','Generate a colour with HEX, RGB and HSL.'],['Random Team','./random-team/','Split names into random teams.'],
    ['Random Letter','./random-letter/','Pick a random A–Z letter.'],['Random Lowercase Letter','./random-lowercase-letter/','Pick a random lowercase letter.'],['Random Emoji','./random-emoji/','Get a surprise emoji.'],['Random Month','./random-month/','Pick a random month.'],['Random Day','./random-day/','Pick a random day.'],['Random Zodiac Sign','./random-zodiac-sign/','Choose a zodiac sign.'],['Random Pokémon','./random-pokemon/','Pick a Pokémon at random.'],['Random Superpower','./random-superpower/','Discover a random superpower.'],['Random Drawing Prompt','./random-drawing-prompt/','Get a fresh idea to draw.'],['Random Writing Prompt','./random-writing-prompt/','Get a creative writing idea.'],['Random Workout','./random-workout/','Get a random workout idea.'],['Random Date Idea','./random-date-idea/','Choose a date idea.'],['Random Holiday Destination','./random-holiday-destination/','Choose somewhere to travel.'],['Random Food Ingredient','./random-food-ingredient/','Pick an ingredient to inspire a dish.'],['Random Colour Name','./random-colour-name/','Pick a colour name.'],['Random Colour HEX','./random-colour-hex/','Pick a colour HEX value.'],['Random Shape','./random-shape/','Pick a shape.'],['Random Season','./random-season/','Pick a season.'],['Random Continent','./random-continent/','Pick a continent.'],['Random Sport','./random-sport/','Pick a sport.'],['Random Animal','./random-animal/','Pick an animal.'],['Random Object','./random-object/','Pick an everyday object.'],['Random Quote','./random-quote/','Get an original short quote.'],['Random Keyboard Key','./random-keyboard-key/','Pick a keyboard key.'],['Random Yes or No Question','./random-yes-or-no-question/','Get a playful yes-or-no prompt.'],
    ['Random Picker','./random-picker/','Pick from your own list.'],['Wheel Spinner','./wheel-spinner/','Spin a real visual wheel.'],['Who Goes First?','./who-goes-first/','Choose a first player fairly.'],['Yes or No','./yes-or-no/','Get a genuinely random yes or no.'],['Random Movie','./random-movie/','Pick a movie by genre.'],['Random Meal','./random-meal/','Choose a meal by type or cuisine.'],['Random Challenge','./random-challenge/','Generate a challenge to try.'],['Random Game','./random-game/','Pick a game for your group.'],['Random Date','./random-date/','Choose a random date in a range.'],
    ['Username Generator','./username-generator/','Create theme-aware usernames.'],['Gamer Name Generator','./gamer-name-generator/','Generate style-based gamer names.'],['Team Name Generator','./team-name-generator/','Create team names by vibe.'],['Fantasy Name Generator','./fantasy-name-generator/','Create fantasy names by style.'],['Pet Name Generator','./pet-name-generator/','Find pet names by vibe.'],['Party Game Generator','./party-game-generator/','Choose a game everyone can play.'],['Secret Santa Picker','./secret-santa-picker/','Make a fair Secret Santa draw.'],['Couples Decision Maker','./couples-decision-maker/','Settle two-option decisions.'],
    ['Random Time','./random-time/','Pick a random time of day.'],['Random Year','./random-year/','Choose a random year.'],['Random Language','./random-language/','Pick a language at random.'],['Random Currency','./random-currency/','Pick a currency at random.'],['Random School Subject','./random-school-subject/','Pick a school subject.'],['Random Job','./random-job/','Discover a random job.'],['Random Board Game','./random-board-game/','Choose a board game to play.'],['Random Playing Card','./random-playing-card/','Draw a random playing card.'],['Random Truth or Dare','./random-truth-or-dare/','Get a ready-to-use prompt.'],['Random Would You Rather','./random-would-you-rather/','Get a would-you-rather question.'],['Random Charades','./random-charades/','Get a charades idea.'],['Random Snack','./random-snack/','Let chance choose your snack.'],['Random Breakfast','./random-breakfast/','Pick a breakfast idea.'],['Random Dessert','./random-dessert/','Choose a dessert.'],['Random Restaurant Cuisine','./random-restaurant-cuisine/','Choose a cuisine.'],['Random Birthstone','./random-birthstone/','Pick a birthstone at random.'],['Random Planet','./random-planet/','Pick a planet.'],['Random Chemical Element','./random-element/','Pick a chemical element.'],['Random Historical Era','./random-era/','Choose an era.'],['Random Activity','./random-activity/','Get a creative activity.'],['Random Classroom Choice','./random-classroom-choice/','Pick a classroom option fairly.']
  ];
  function read(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return[]}}
  function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(e){}}
  function secureIndex(max){if(max<=0)return 0;if(window.crypto&&window.crypto.getRandomValues){var a=new Uint32Array(1),span=max+1,limit=Math.floor(4294967296/span)*span,v;do{window.crypto.getRandomValues(a);v=a[0]}while(v>=limit);return v%span}return Math.floor(Math.random()*(max+1))}
  function esc(s){return String(s).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
  function favourites(){return read(FAV_KEY)}
  function recent(){return read(RECENT_KEY)}
  function addRecent(url){var r=recent().filter(function(x){return x!==url});r.unshift(url);write(RECENT_KEY,r.slice(0,12))}
  function isFavourite(url){return favourites().indexOf(url)!==-1}
  function toggleFavourite(url){var f=favourites();if(f.indexOf(url)!==-1)f=f.filter(function(x){return x!==url});else f.unshift(url);write(FAV_KEY,f.slice(0,50));renderDirectory();renderUtilities();renderSearch()}
  function toolCard(t){return '<a class="tool-card v3-card" href="'+t[1]+'" data-name="'+esc(t[0].toLowerCase())+'" data-desc="'+esc(t[2].toLowerCase())+'"><span class="v3-card-top"><b>'+esc(t[0])+'</b><button type="button" class="fav-btn '+(isFavourite(t[1])?'is-fav':'')+'" data-fav="'+t[1]+'" aria-label="'+(isFavourite(t[1])?'Remove from favourites':'Add to favourites')+'">'+(isFavourite(t[1])?'★':'☆')+'</button></span><span>'+esc(t[2])+'</span></a>'}
  function toolIcon(name){var n=name.toLowerCase();if(n.indexOf('game')!==-1||n.indexOf('gamer')!==-1)return '🎮';if(n.indexOf('name')!==-1)return '✨';if(n.indexOf('food')!==-1||n.indexOf('meal')!==-1||n.indexOf('snack')!==-1||n.indexOf('breakfast')!==-1||n.indexOf('dessert')!==-1||n.indexOf('cuisine')!==-1)return '🍴';if(n.indexOf('country')!==-1||n.indexOf('continent')!==-1||n.indexOf('destination')!==-1)return '🌍';if(n.indexOf('colour')!==-1||n.indexOf('color')!==-1)return '🎨';if(n.indexOf('wheel')!==-1)return '🎡';if(n.indexOf('movie')!==-1)return '🎬';if(n.indexOf('word')!==-1||n.indexOf('letter')!==-1)return '🔤';if(n.indexOf('workout')!==-1||n.indexOf('sport')!==-1)return '💪';if(n.indexOf('school')!==-1||n.indexOf('classroom')!==-1||n.indexOf('subject')!==-1)return '📚';if(n.indexOf('decision')!==-1||n.indexOf('yes or no')!==-1||n.indexOf('picker')!==-1)return '✅';if(n.indexOf('date')!==-1||n.indexOf('time')!==-1||n.indexOf('year')!==-1)return '📅';if(n.indexOf('random number')!==-1||n.indexOf('dice')!==-1)return '🎲';if(n.indexOf('animal')!==-1||n.indexOf('pet')!==-1)return '🐾';if(n.indexOf('writing')!==-1||n.indexOf('drawing')!==-1||n.indexOf('prompt')!==-1||n.indexOf('creative')!==-1)return '💡';return '✦'}
  function bindCards(){document.querySelectorAll('[data-fav]').forEach(function(btn){if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();toggleFavourite(btn.getAttribute('data-fav'))})});document.querySelectorAll('.v3-card').forEach(function(card){if(card.dataset.recentBound)return;card.dataset.recentBound='1';card.addEventListener('click',function(){addRecent(card.getAttribute('href'))})})}
  function renderDirectory(){var dir=document.getElementById('v3-directory');if(!dir)return;dir.innerHTML=TOOLS.map(toolCard).join('');bindCards()}
  function renderUtilities(){var host=document.getElementById('v3-tools');if(!host)return;var r=recent(),f=favourites();function block(items,title,empty){if(!items.length)return '<section class="v3-mini"><div class="v3-mini-head"><span>'+title+'</span></div><p class="v3-empty">'+empty+'</p></section>';return '<section class="v3-mini"><div class="v3-mini-head"><span>'+title+'</span></div><div class="v3-mini-grid">'+items.map(function(url){var t=TOOLS.filter(function(x){return x[1]===url})[0];return t?'<a class="v3-mini-card" href="'+t[1]+'"><span>'+esc(t[0])+'</span><small>'+esc(t[2])+'</small></a>':''}).join('')+'</div></section>'}host.innerHTML=block(r,'Recently used','Your recent tools will appear here.')+block(f,'Favourites','Star a tool to keep it here.');}
  function renderSearch(){var input=document.getElementById('v3-search'),count=document.getElementById('v3-search-count'),results=document.getElementById('v3-search-results');if(!input||!results)return;var q=input.value.toLowerCase().trim();var matches=q?TOOLS.filter(function(t){return (t[0]+' '+t[2]).toLowerCase().indexOf(q)!==-1}):[];if(count)count.textContent=q?(matches.length+' tool'+(matches.length===1?'':'s')+' found'):'';if(!q){results.innerHTML='';results.classList.remove('has-results');return}if(!matches.length){results.innerHTML='<div class="search-empty"><span class="search-empty-icon">🔎</span><div><strong>No tools found</strong><small>Try <em>games</em>, <em>names</em>, <em>food</em>, <em>school</em> or <em>random</em>.</small></div></div>';results.classList.add('has-results');return}results.innerHTML='<div class="search-results-heading"><strong>'+matches.length+' '+(matches.length===1?'match':'matches')+'</strong><span>Pick one to open it</span></div><div class="search-results-grid">'+matches.map(function(t){return '<a class="search-result-card" href="'+t[1]+'" data-search-url="'+t[1]+'"><span class="search-result-icon">'+toolIcon(t[0])+'</span><span class="search-result-copy"><b>'+esc(t[0])+'</b><small>'+esc(t[2])+'</small></span><span class="search-result-arrow">→</span></a>'}).join('')+'</div>';results.classList.add('has-results');results.querySelectorAll('a[data-search-url]').forEach(function(a){a.addEventListener('click',function(){addRecent(a.getAttribute('href'))})})}
  function bindSearch(){var input=document.getElementById('v3-search');if(!input||input.dataset.v5bound)return;input.dataset.v5bound='1';input.addEventListener('input',renderSearch);renderSearch()}
  function bindSurprise(){['surpriseBtn','surpriseBtn2'].forEach(function(id){var b=document.getElementById(id);if(!b||b.dataset.v5bound)return;b.dataset.v5bound='1';b.addEventListener('click',function(){var t=TOOLS[secureIndex(TOOLS.length-1)];addRecent(t[1]);b.classList.add('is-spinning');setTimeout(function(){window.location.href=t[1]},180)})})}
  function bindShare(){var b=document.getElementById('shareSite');if(!b||b.dataset.v5bound)return;b.dataset.v5bound='1';b.addEventListener('click',function(){var u=window.location.href;if(navigator.share)navigator.share({title:'RandoSpino',text:"Can't decide? Let RandoSpino choose.",url:u}).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(u).then(function(){var old=b.textContent;b.textContent='Link copied ✓';setTimeout(function(){b.textContent=old},1200)})})}
  function boot(){renderDirectory();renderUtilities();bindSearch();bindSurprise();bindShare()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
