(function(){'use strict';
var pools={
  letters:'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  emojis:['😀','😂','😍','😎','🤔','🥳','😇','🤩','😴','🤯','😱','🥹','😈','👑','🔥','⭐','🌈','🍀','🎯','🎲','🎉','🚀','🌙','☀️','🍕','🍔','🍩','🍎','🐶','🐱','🦊','🐼','🦄','🐸','🦁','🐢','🌍','🏖️','⚽','🎮'],
  months:['January','February','March','April','May','June','July','August','September','October','November','December'],
  days:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  zodiac:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
  superpowers:['Teleportation','Time travel','Invisibility','Flying','Super strength','Mind reading','Shape-shifting','Healing','Telekinesis','Talking to animals','Controlling weather','Super speed','Creating portals','Perfect memory','Underwater breathing','Night vision','Freezing time','Luck manipulation','Instant learning','Communicating with plants'],
  pokemon:['Bulbasaur','Charmander','Squirtle','Pikachu','Jigglypuff','Meowth','Psyduck','Eevee','Snorlax','Mewtwo','Chikorita','Cyndaquil','Totodile','Lugia','Celebi','Treecko','Torchic','Mudkip','Gardevoir','Rayquaza','Turtwig','Chimchar','Piplup','Lucario','Gible','Snivy','Tepig','Oshawott','Zorua','Greninja','Fennekin','Froakie','Rowlet','Litten','Popplio','Mimikyu','Grookey','Scorbunny','Sobble','Wooloo','Sprigatito','Fuecoco','Quaxly'],
  drawing:['A tiny dragon','A futuristic city','A magical library','A robot pet','A haunted house','A floating island','An underwater kingdom','A superhero costume','A giant friendly monster','A dream bedroom','A space station','A secret garden','A fantasy tavern','A time machine','A treasure map','A talking cat','A mythical sword','A cosy cabin','An alien market','A magical school'],
  writing:['Write a story that starts with a mysterious package','Describe a city where nobody can lie','Write from the perspective of a forgotten toy','Create a character who can hear colours','Write a letter from the future','Describe the perfect impossible holiday','Write a story set during a power cut','Create a villain who wants to make everyone happy','Write six sentences without using the letter E','Describe a door that has never been opened'],
  workouts:['20 bodyweight squats','30-second plank','10 reverse lunges each side','15 incline push-ups','20 glute bridges','30 jumping jacks','10 burpees','20 calf raises','30-second wall sit','15 mountain climbers each side','10 push-ups','20 high knees','30-second hollow hold','15 sit-ups','10 walkout repetitions'],
  dateIdeas:['Coffee and a walk','Cook a new recipe together','Visit a museum','Mini golf','Sunset picnic','Board-game café','Movie night with homemade snacks','Try a new restaurant','Bookshop date','Go bowling','Take a scenic train ride','Visit a local market','Make pizzas together','Do a photo challenge','Try an escape room'],
  holidays:['Lisbon','Barcelona','Rome','Prague','Amsterdam','Athens','Istanbul','Copenhagen','Reykjavik','Marrakesh','Dubai','Tokyo','Seoul','Bangkok','Singapore','Bali','New York','Vancouver','Mexico City','Rio de Janeiro'],
  ingredients:['Tomatoes','Garlic','Ginger','Spinach','Chickpeas','Mushrooms','Lemons','Avocado','Sweetcorn','Courgette','Aubergine','Coconut milk','Basil','Coriander','Feta','Mozzarella','Lentils','Black beans','Bell peppers','Sweet potato']
};
var tools={
 randomLetter:{title:'Random Letter Generator',desc:'Pick a random letter from A to Z.',pool:pools.letters},randomEmoji:{title:'Random Emoji Generator',desc:'Get a random emoji instantly.',pool:pools.emojis},randomMonth:{title:'Random Month Generator',desc:'Pick a random month.',pool:pools.months},randomDay:{title:'Random Day Generator',desc:'Pick a random day of the week.',pool:pools.days},randomZodiac:{title:'Random Zodiac Sign Generator',desc:'Pick a zodiac sign at random.',pool:pools.zodiac},randomSuperpower:{title:'Random Superpower Generator',desc:'Discover a superpower you might want.',pool:pools.superpowers},randomPokemon:{title:'Random Pokémon Generator',desc:'Pick a Pokémon at random.',pool:pools.pokemon},randomDrawingPrompt:{title:'Random Drawing Prompt Generator',desc:'Get a fresh idea to draw.',pool:pools.drawing},randomWritingPrompt:{title:'Random Writing Prompt Generator',desc:'Get a creative prompt and start writing.',pool:pools.writing},randomWorkout:{title:'Random Workout Generator',desc:'Get a simple exercise to try.',pool:pools.workouts},randomDateIdea:{title:'Random Date Idea Generator',desc:'Let chance choose your next date.',pool:pools.dateIdeas},randomHolidayDestination:{title:'Random Holiday Destination Generator',desc:'Choose somewhere to travel.',pool:pools.holidays},randomFoodIngredient:{title:'Random Food Ingredient Generator',desc:'Pick an ingredient to inspire your next dish.',pool:pools.ingredients}
};
function secure(){var a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]}function pick(a){return a[Math.floor((secure()/4294967296)*a.length)]}function boot(){var key=document.body.getAttribute('data-tool'),t=tools[key];if(!t)return;var title=document.getElementById('tool-title'),desc=document.getElementById('tool-desc'),run=document.getElementById('run'),out=document.getElementById('result');if(!title||!desc||!run||!out)return;title.textContent=t.title;desc.textContent=t.desc;run.onclick=function(){var value=pick(t.pool);out.className='result';out.innerHTML='<div class="result-main">'+String(value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})+'</div>'};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
