(function(){
  'use strict';
  function init(){
    var controls=document.getElementById('controls'),run=document.getElementById('run');
    if(!controls||!run)return;
    var timer=setInterval(function(){
      var canvas=document.getElementById('wheelCanvas'),input=document.getElementById('items');
      if(!canvas||!input)return;
      clearInterval(timer);
      var remove=document.getElementById('removeWinner');
      var ctx=canvas.getContext('2d'),rotation=0,spinning=false,sound=true;
      function r32(){var a=new Uint32Array(1);window.crypto.getRandomValues(a);return a[0];}
      function rint(min,max){var span=max-min+1,lim=Math.floor(4294967296/span)*span,v;do{v=r32();}while(v>=lim);return min+(v%span);}
      function values(){return input.value.split(/[\n,]+/).map(function(x){return x.trim();}).filter(Boolean).filter(function(v,i,a){return a.indexOf(v)===i;});}
      function draw(){var a=values();if(!a.length)a=['Add entries'];var dpr=window.devicePixelRatio||1,w=canvas.clientWidth||520;canvas.width=w*dpr;canvas.height=w*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,w);var cx=w/2,cy=w/2,r=w/2-12,s=2*Math.PI/a.length;ctx.save();ctx.translate(cx,cy);var colors=['#6b57f1','#ff5f98','#14b8a6','#f59e0b','#06b6d4','#8b5cf6','#ef4444','#22c55e','#3b82f6','#ec4899','#84cc16','#f97316'];a.forEach(function(item,i){var start=-Math.PI/2+i*s,end=start+s;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,start,end);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.strokeStyle='rgba(255,255,255,.92)';ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.rotate(start+s/2);ctx.fillStyle='#fff';ctx.font=(a.length>12?'12px':'15px')+' Inter,Arial,sans-serif';ctx.fontWeight='800';ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillText(item.length>19?item.slice(0,18)+'…':item,r-18,0);ctx.restore();});ctx.beginPath();ctx.arc(0,0,42,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='rgba(25,27,45,.10)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#171827';ctx.font='800 14px Inter,Arial,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('RAND',0,-4);ctx.fillText('SPINO',0,12);ctx.restore();}
      function sync(){draw();canvas.style.transform='rotate('+rotation+'deg)';}
      function beep(){if(!sound)return;try{var A=window.AudioContext||window.webkitAudioContext;if(!A)return;var ac=new A(),o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.value=620;g.gain.setValueAtTime(.0001,ac.currentTime);g.gain.exponentialRampToValueAtTime(.08,ac.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.16);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.17);}catch(e){}}
      function celebrate(){var layer=document.createElement('div');layer.className='wheel-confetti';for(var i=0;i<26;i++){var s=document.createElement('span');s.textContent=['✦','●','◆','★'][i%4];s.style.left=(8+rint(0,84))+'%';s.style.top=(8+rint(0,20))+'%';s.style.setProperty('--dx',(rint(-180,180))+'px');s.style.setProperty('--dy',(rint(180,460))+'px');s.style.animationDelay=(rint(0,220)/100)+'s';layer.appendChild(s);}document.body.appendChild(layer);setTimeout(function(){layer.remove();},2100);}
      function addControls(){var box=document.createElement('div');box.className='wheel-v2-controls';box.innerHTML='<div class="wheel-presets"><span>Quick presets</span><button type="button" data-preset="Dinner">🍕 Dinner</button><button type="button" data-preset="Party">🎉 Party</button><button type="button" data-preset="Classroom">📚 Classroom</button><button type="button" data-preset="Games">🎮 Games</button></div><label class="check-row"><input id="wheelSound" type="checkbox" checked> Sound on spin</label>';controls.appendChild(box);var map={Dinner:['Pizza','Burgers','Indian','Chinese','Mexican','Pasta','Sushi'],Party:['Charades','Truth or Dare','Would You Rather','Pictionary','Trivia','Music Quiz','Two Truths and a Lie'],Classroom:['Discussion leader','Next presenter','Team captain','Timekeeper','Recorder','First speaker','Warm-up activity'],Games:['Minecraft','Mario Kart','Fortnite','Uno','Chess','Monopoly','Among Us','Rocket League']};box.querySelectorAll('[data-preset]').forEach(function(b){b.onclick=function(){input.value=map[b.dataset.preset].join('\n');sync();};});var soundBox=document.getElementById('wheelSound');soundBox.addEventListener('change',function(){sound=soundBox.checked;});}
      function appendResult(out,winner){out.className='result';out.innerHTML='<div class="result-main">🎡 '+escapeHtml(winner)+'</div><div class="wheel-result-actions"><button type="button" class="copy-result">Copy result</button><button type="button" class="secondary-action">Share result</button></div>';var copy=out.querySelector('.copy-result');copy.onclick=function(){navigator.clipboard&&navigator.clipboard.writeText(winner).then(function(){copy.textContent='Copied ✓';setTimeout(function(){copy.textContent='Copy result';},1000);});};var share=out.querySelector('.secondary-action');share.onclick=function(){var data={title:'RandoSpino result',text:'RandoSpino chose: '+winner,url:location.href};if(navigator.share)navigator.share(data).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText('RandoSpino chose: '+winner).then(function(){share.textContent='Copied ✓';setTimeout(function(){share.textContent='Share result';},1000);});};}
      function escapeHtml(v){return String(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
      input.addEventListener('input',sync);window.addEventListener('resize',sync);addControls();sync();
      run.addEventListener('click',function(){if(spinning)return;var a=values(),out=document.getElementById('result');if(a.length<2){out.className='result error-result';out.textContent='Add at least two entries for the wheel.';return;}spinning=true;run.disabled=true;var winner=rint(0,a.length-1),slice=360/a.length,center=winner*slice+slice/2,delta=((360-center-(rotation%360))+360)%360+360*5+rint(0,2)*360,target=rotation+delta;canvas.style.transition='transform 1.8s cubic-bezier(.12,.74,.22,1)';canvas.style.transform='rotate('+target+'deg)';beep();setTimeout(function(){rotation=target%360;canvas.style.transition='none';canvas.style.transform='rotate('+rotation+'deg)';appendResult(out,a[winner]);celebrate();if(window.RandoSpinoAnalytics)window.RandoSpinoAnalytics.event('wheel_spin',{winner:a[winner]});if(remove&&remove.checked){a.splice(winner,1);input.value=a.join('\n');sync();}spinning=false;run.disabled=false;},1850);});
    },50);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
